// Generated by CoffeeScript 1.4.0
(function() {
  var aliasField;

  aliasField = require('mongoose-aliasfield');

  module.exports = function(schema, options) {
    schema.plugin(aliasField);
    return schema.methods.toJSON = function() {
      var obj;
      obj = this.toAliasedFieldsObject();
      obj.id = obj._id;
      delete obj._id;
      return obj;
    };
  };

}).call(this);
